<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id(); // Primary key
            $table->string('name'); // User name
            $table->string('email')->unique(); // Unique email
            $table->string('password'); // Password
            $table->string('s_number')->unique(); // Unique student number or teacher ID
            $table->enum('role', ['student', 'Lecturer']); // Role to distinguish between student and teacher
            $table->string('profile_photo')->nullable()->default('default_photo.jpg');
            $table->unsignedBigInteger('group_id')->nullable();
            $table->foreign('group_id')->references('id')->on('groups')->onDelete('set null');
            $table->rememberToken(); // autogenerated
            $table->timestamps(); // auto generated
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
